name: sos_mobile_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# ---------------------------------------------------------------- #
version: 1.0.0+1
# ---------------------------------------------------------------- #
environment:
  sdk: ">=2.17.1 <3.0.0"
# ---------------------------------------------------------------- #
dependencies:
  flutter:
    sdk: flutter
# ---------------------------------------------------------------- #
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_dotenv: ^5.0.2
  get_storage: ^2.0.3
  # support svg icon format 
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.1
  url_launcher: ^6.1.3
  image_picker: ^0.8.5+3
  timelines: ^0.1.0
  flutter_launcher_icons: ^0.9.3
# ---------------------------------------------------------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter
# ---------------------------------------------------------------- #
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
